### ISSUE TITLE
PAGE_XPATH配置问题

### ISSUE THREAD

**Issue by lls-github** [ShichaoMa/webWalker#1]
您好
我是python新手，git也不是很清楚具体怎么用，不知道在这里留言是否合适
从这里看到的帖子
https://zhuanlan.zhihu.com/p/23178014?refer=zimei
我想试着爬一下http://desk.zol.com.cn/fengjing/ 中的图片
在配置PAGE_XPATH时遇到一些问题，请指教
```
PAGE_XPATH = {
    "ZOL": [
        '//li[@class="photo-list-padding"]/a[@class="pic"]/@href',
    ]
}
```
浏览器返回的地址为/bizhi/6846_85460_2.html...
其实际地址应为http://desk.zol.com.cn + 上面的返回值
这里不知道该如何来写

**Comment by ShichaoMa** [comment]
你这个没有关系的，我里面代码中有一步逻辑是这样的, urljoin(response.url, "/bizhi/6846_85460_2.html")， 可以拼接成完整的url
